namespace Enactive.Engine.Tests;

using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using Enactive.Remote.Contracts;
using Enactive.Remote.Contracts.Crypto;
using Xunit;

/// <summary>
/// The shared vectors that pin the C# and the JS (browser) cryptography to the same bytes. The file
/// tests/vectors/remote-crypto-v2.json holds fixed inputs and the outputs the C# code produced from them;
/// the JS tests of the panel load the same file and must reproduce every output byte for byte. Without a
/// shared file the two implementations could each pass their own tests and still not open each other's
/// envelopes, which only shows once a real browser talks to a real Host.
/// </summary>
public sealed class RemoteVectorsTests
{
    private const string FormatVersion = "remote-crypto-v2";
    private const string FileName = "remote-crypto-v2.json";
    private const string UpdateVariable = "ENACTIVE_UPDATE_VECTORS";
    private const string Note = "Generated by RemoteVectorsTests.Regenerate_vectors from C# (Enactive.Remote.Contracts); do not edit by hand. "
        + "Binary values are base64url without padding; plaintext, canonical fields and ids are plain text; private keys are JWK-style base64url d, x, y.";

    // Compact on purpose: the comparison is between serialised sections, so the same writer must serve both sides.
    private static readonly JsonSerializerOptions Compact = new() { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    // Relaxed escaping keeps the non-ASCII vectors readable in the file; the newline is pinned to LF so the file does not change with the platform that regenerated it.
    private static readonly JsonSerializerOptions Pretty = new()
    {
        WriteIndented = true,
        NewLine = "\n",
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };

    [Fact]
    public void Vectors_are_reproduced()
    {
        var stored = JsonNode.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, FileName)))!.AsObject();
        var recomputed = Compute(stored);

        Assert.Equal(recomputed.Select(p => p.Key), stored.Select(p => p.Key));
        foreach (var (key, value) in recomputed)
        {
            var expected = stored[key]!.ToJsonString(Compact);
            var actual = value!.ToJsonString(Compact);
            Assert.True(expected == actual, $"The vectors for '{key}' were not reproduced.\n  stored:   {expected}\n  computed: {actual}");
        }
    }

    /// <summary>
    /// The vectors are not only recomputed but used: the sealed text opens, the grant yields the host key, the
    /// MAC verifies and the code parses back. A set of outputs that merely matched themselves could still be
    /// unusable by a receiver.
    /// </summary>
    [Fact]
    public void Vectors_are_usable_by_the_receiving_side()
    {
        var stored = JsonNode.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, FileName)))!.AsObject();

        foreach (var item in stored["envelope"]!.AsArray())
        {
            var opened = Envelope.Open(Binary(item!, "key"), Text(item!, "sealed"), Binary(item!, "ad"));
            Assert.Equal(Text(item!, "plaintext"), Encoding.UTF8.GetString(opened));
        }

        var hostKey = stored["hostKey"]!;
        var grant = stored["grant"]!;
        var wire = grant["grant"]!;
        using var device = Import(grant["devicePrivate"]!);
        var opening = new KeyGrant(Text(wire, "hostId"), Text(wire, "deviceId"), wire["epoch"]!.GetValue<uint>(),
            Text(wire, "ephemeralPublic"), Text(wire, "nonce"), Text(wire, "ciphertext"), Text(wire, "authBy"), Text(wire, "mac"));
        var recovered = Grants.Open(opening, device, Binary(grant, "pairKey"));
        Assert.Equal(Binary(hostKey, "secret"), recovered.Secret.ToArray());

        var enrollment = stored["enrollment"]!;
        Assert.True(Enrollment.Verify(Binary(enrollment, "pairKey"), Text(enrollment, "inviteId"), Text(enrollment, "deviceId"),
            Binary(enrollment, "devicePublic"), Text(enrollment, "mac")));

        var code = ConnectionCode.Parse(Text(stored["connectionCode"]!, "text"));
        Assert.Equal(Text(stored["connectionCode"]!, "hostId"), code.HostId);
        Assert.Equal(Binary(stored["connectionCode"]!, "pairingSecret"), code.PairingSecret);

        var invite = InviteLink.Parse(Text(stored["inviteLink"]!, "text"));
        Assert.Equal(Text(stored["inviteLink"]!, "inviteId"), invite.InviteId);
        Assert.Equal(Binary(stored["inviteLink"]!, "secret"), invite.PairingSecret);
    }

    /// <summary>
    /// Regenerating changes every value the JS tests compare; do it only when the format version changes.
    /// It runs only on request (ENACTIVE_UPDATE_VECTORS=1), so an ordinary test run can never rewrite the
    /// file the JS side was written against.
    /// </summary>
    [Fact]
    public void Regenerate_vectors()
    {
        if (Environment.GetEnvironmentVariable(UpdateVariable) != "1") return;

        var path = Path.Combine(TestRepository.Root, "tests", "vectors", FileName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Compute(Fresh()).ToJsonString(Pretty) + "\n", new UTF8Encoding(false));
    }

    // ---- what the vectors contain -------------------------------------------------------------------------

    /// <summary>Fresh random inputs; the outputs are filled in by <see cref="Compute"/>, exactly as when the file is checked.</summary>
    private static JsonObject Fresh()
    {
        const string gateway = "https://remote.example.com";
        const string hostId = "host-7f3a9c";
        const string deviceId = "device-b41e02";

        using var device = P256.Generate();
        using var ephemeral = P256.Generate();
        using var enrolled = P256.Generate();
        var hostSecret = RandomNumberGenerator.GetBytes(32);
        const uint epoch = 3;
        var hostKey = HostKey.From(epoch, hostSecret);

        var pairingSecret = RandomNumberGenerator.GetBytes(32);
        var devicePublic = P256.PublicRaw(device);
        var code = new ConnectionCode(new Uri(gateway), hostId, Convert.ToHexStringLower(RandomNumberGenerator.GetBytes(32)),
            deviceId, devicePublic, pairingSecret);
        var invite = new InviteLink(new Uri(gateway), "invite 7/ü+x", RandomNumberGenerator.GetBytes(32));

        const string taskId = "task-0042";
        const string workspaceId = "ws-main";
        const string runId = "run-0001";
        const string toolCallId = "call_abc123";
        const string actionHash = "9f2c0e4b7a1d3c58e6b0a49d2f7183c5d0e8a6b4c2f1907e3d5a8b6c4e2f0a19";

        return new JsonObject
        {
            ["version"] = FormatVersion,
            ["note"] = Note,
            ["canonical"] = new JsonArray(
                CanonicalCase("enactive-task-v1", "host-1", "task-1", "ws-1"),
                CanonicalCase("enactive-test-v1"),
                CanonicalCase("enactive-test-v1", "", "a", ""),
                CanonicalCase("enactive-test-v1", "a\n1:b"),
                CanonicalCase("enactive-test-v1", "é", "日本語", "🙂 smile", "line one\nline two\r\nline three")),
            ["kdf"] = new JsonArray(
                KdfCase(RemoteKdf.Message),
                KdfCase(RemoteKdf.GrantAuth),
                KdfCase(RemoteKdf.Pair),
                KdfCase(Canonical.Bytes("enactive-grant-v1", hostId, deviceId, "3", "ephemeral", "device"))),
            ["envelope"] = new JsonArray(
                EnvelopeCase(hostKey.MessageKey, epoch, Ad.Task(hostId, taskId, workspaceId),
                    "{\"title\":\"Rotate the nightly backup\",\"prompt\":\"Check disk usage on D:\\\\ and report folders over 10 GB.\"}"),
                EnvelopeCase(RandomNumberGenerator.GetBytes(32), 0, Ad.Command(hostId, "cmd-0009", CommandKind.StartTask), ""),
                EnvelopeCase(RandomNumberGenerator.GetBytes(32), uint.MaxValue,
                    Ad.Event(hostId, runId, 12, RemoteEventKind.Progress), "Привет, мир — 日本語 🙂 café\nвторая строка"),
                EnvelopeCase(RandomNumberGenerator.GetBytes(32), 1, Ad.Workspace(hostId, workspaceId),
                    string.Concat(Enumerable.Repeat("0123456789abcdef", 20)))),
            ["hostKey"] = new JsonObject { ["epoch"] = epoch, ["secret"] = B64.Url(hostSecret) },
            ["grant"] = new JsonObject
            {
                ["hostId"] = hostId,
                ["deviceId"] = deviceId,
                ["authBy"] = Grants.AuthByPairing("connect"),
                ["devicePrivate"] = Export(device),
                ["ephemeralPrivate"] = Export(ephemeral),
                ["nonce"] = B64.Url(RandomNumberGenerator.GetBytes(12)),
                ["pairKey"] = B64.Url(code.PairKey)
            },
            ["enrollment"] = new JsonObject
            {
                ["pairKey"] = B64.Url(invite.PairKey),
                ["inviteId"] = invite.InviteId,
                ["deviceId"] = "device-c9d814",
                ["devicePublic"] = B64.Url(P256.PublicRaw(enrolled))
            },
            // The same run and call written with a trailing backslash and with forward slashes: the first two hash alike by design.
            ["actionIdentity"] = new JsonArray(
                ActionCase(runId, toolCallId, "run_command", "C:\\work\\project\\", "{\"command\":\"dotnet test\"}"),
                ActionCase(runId, toolCallId, "run_command", "C:/work/project", "{\"command\":\"dotnet test\"}"),
                ActionCase("run-0002", "call_def456", "write_file", "C:\\", "{\"path\":\"Отчёт.txt\",\"content\":\"line1\\nline2 — 🙂\"}"),
                ActionCase("run-0003", "call_ghi789", "read_file", "", "{ \"path\" : \"/etc/hosts\" }"),
                ActionCase("run-0004", "call_jkl012", "run_command", "/home/user/work/", "{\"command\":\"echo 'a:b' | wc -c\"}")),
            ["connectionCode"] = new JsonObject
            {
                ["gateway"] = gateway,
                ["hostId"] = hostId,
                ["token"] = code.Token,
                ["deviceId"] = deviceId,
                ["devicePublic"] = B64.Url(devicePublic),
                ["pairingSecret"] = B64.Url(pairingSecret)
            },
            ["inviteLink"] = new JsonObject
            {
                ["gateway"] = gateway,
                ["inviteId"] = invite.InviteId,
                ["secret"] = B64.Url(invite.PairingSecret)
            },
            ["ad"] = new JsonArray(
                new JsonObject
                {
                    ["builder"] = "task",
                    ["args"] = new JsonObject { ["hostId"] = hostId, ["taskId"] = taskId, ["workspaceId"] = workspaceId }
                },
                new JsonObject
                {
                    ["builder"] = "command",
                    ["args"] = new JsonObject { ["hostId"] = hostId, ["commandId"] = "cmd-0009", ["kind"] = nameof(CommandKind.StartTask) }
                },
                // Beyond 2^32 so a browser that held the sequence in a 32-bit integer would be caught.
                new JsonObject
                {
                    ["builder"] = "event",
                    ["args"] = new JsonObject
                    {
                        ["hostId"] = hostId, ["runId"] = runId, ["sequence"] = 4294967297, ["kind"] = nameof(RemoteEventKind.Progress)
                    }
                },
                ApprovalCase(hostId, runId, "appr-0001", toolCallId, actionHash, true),
                ApprovalCase(hostId, runId, "appr-0002", "call_def456", actionHash, false),
                new JsonObject
                {
                    ["builder"] = "workspace",
                    ["args"] = new JsonObject { ["hostId"] = hostId, ["workspaceId"] = "ws-проект-日本" }
                })
        };
    }

    /// <summary>
    /// The one place the outputs are produced. It reads only inputs from <paramref name="input"/> (any output
    /// already in it is ignored), so regenerating and checking cannot disagree about how a value is computed.
    /// </summary>
    private static JsonObject Compute(JsonObject input) => new()
    {
        ["version"] = FormatVersion,
        ["note"] = Note,
        ["canonical"] = Each(input["canonical"], item =>
        {
            var fields = item["fields"]!.AsArray().Select(f => f!.GetValue<string>()).ToArray();
            return new JsonObject
            {
                ["version"] = Text(item, "version"),
                ["fields"] = item["fields"]!.DeepClone(),
                ["text"] = Canonical.Text(Text(item, "version"), fields)
            };
        }),
        ["kdf"] = Each(input["kdf"], item => new JsonObject
        {
            ["ikm"] = Text(item, "ikm"),
            ["info"] = Text(item, "info"),
            ["out"] = B64.Url(RemoteKdf.Derive(Binary(item, "ikm"), Binary(item, "info").AsSpan()))
        }),
        ["envelope"] = Each(input["envelope"], item => new JsonObject
        {
            ["key"] = Text(item, "key"),
            ["epoch"] = item["epoch"]!.GetValue<uint>(),
            ["nonce"] = Text(item, "nonce"),
            ["ad"] = Text(item, "ad"),
            ["plaintext"] = Text(item, "plaintext"),
            ["sealed"] = Envelope.Seal(Binary(item, "key"), item["epoch"]!.GetValue<uint>(),
                Encoding.UTF8.GetBytes(Text(item, "plaintext")), Binary(item, "ad"), Binary(item, "nonce"))
        }),
        ["hostKey"] = ComputeHostKey(input["hostKey"]!),
        ["grant"] = ComputeGrant(input["grant"]!, input["hostKey"]!),
        ["enrollment"] = ComputeEnrollment(input["enrollment"]!),
        ["actionIdentity"] = Each(input["actionIdentity"], item => new JsonObject
        {
            ["runId"] = Text(item, "runId"),
            ["toolCallId"] = Text(item, "toolCallId"),
            ["tool"] = Text(item, "tool"),
            ["workingDirectory"] = Text(item, "workingDirectory"),
            ["argumentsJson"] = Text(item, "argumentsJson"),
            ["hash"] = ActionIdentity.Hash(Text(item, "runId"), Text(item, "toolCallId"), Text(item, "tool"),
                Text(item, "workingDirectory"), Text(item, "argumentsJson"))
        }),
        ["connectionCode"] = ComputeConnectionCode(input["connectionCode"]!),
        ["inviteLink"] = ComputeInviteLink(input["inviteLink"]!),
        ["ad"] = Each(input["ad"], ComputeAd)
    };

    private static JsonObject ComputeHostKey(JsonNode input)
    {
        var key = HostKey.From(input["epoch"]!.GetValue<uint>(), Binary(input, "secret"));
        return new JsonObject
        {
            ["epoch"] = key.Epoch,
            ["secret"] = Text(input, "secret"),
            ["messageKey"] = B64.Url(key.MessageKey),
            ["grantAuthKey"] = B64.Url(key.GrantAuthKey)
        };
    }

    private static JsonObject ComputeGrant(JsonNode input, JsonNode hostKeyInput)
    {
        var hostKey = HostKey.From(hostKeyInput["epoch"]!.GetValue<uint>(), Binary(hostKeyInput, "secret"));
        using var device = Import(input["devicePrivate"]!);
        using var ephemeral = Import(input["ephemeralPrivate"]!);
        var devicePublic = P256.PublicRaw(device);
        var grant = Grants.Create(Text(input, "hostId"), Text(input, "deviceId"), devicePublic, hostKey,
            Text(input, "authBy"), Binary(input, "pairKey"), ephemeral, Binary(input, "nonce"));
        return new JsonObject
        {
            ["hostId"] = Text(input, "hostId"),
            ["deviceId"] = Text(input, "deviceId"),
            ["authBy"] = Text(input, "authBy"),
            ["devicePrivate"] = input["devicePrivate"]!.DeepClone(),
            ["devicePublic"] = B64.Url(devicePublic),
            ["ephemeralPrivate"] = input["ephemeralPrivate"]!.DeepClone(),
            ["nonce"] = Text(input, "nonce"),
            ["pairKey"] = Text(input, "pairKey"),
            ["grant"] = new JsonObject
            {
                ["hostId"] = grant.HostId,
                ["deviceId"] = grant.DeviceId,
                ["epoch"] = grant.Epoch,
                ["ephemeralPublic"] = grant.EphemeralPublic,
                ["nonce"] = grant.Nonce,
                ["ciphertext"] = grant.Ciphertext,
                ["authBy"] = grant.AuthBy,
                ["mac"] = grant.Mac
            }
        };
    }

    private static JsonObject ComputeEnrollment(JsonNode input) => new()
    {
        ["pairKey"] = Text(input, "pairKey"),
        ["inviteId"] = Text(input, "inviteId"),
        ["deviceId"] = Text(input, "deviceId"),
        ["devicePublic"] = Text(input, "devicePublic"),
        ["mac"] = Enrollment.Mac(Binary(input, "pairKey"), Text(input, "inviteId"), Text(input, "deviceId"), Binary(input, "devicePublic"))
    };

    private static JsonObject ComputeConnectionCode(JsonNode input)
    {
        var code = new ConnectionCode(new Uri(Text(input, "gateway")), Text(input, "hostId"), Text(input, "token"),
            Text(input, "deviceId"), Binary(input, "devicePublic"), Binary(input, "pairingSecret"));
        return new JsonObject
        {
            ["gateway"] = Text(input, "gateway"),
            ["hostId"] = code.HostId,
            ["token"] = code.Token,
            ["deviceId"] = code.DeviceId,
            ["devicePublic"] = Text(input, "devicePublic"),
            ["pairingSecret"] = Text(input, "pairingSecret"),
            ["pairKey"] = B64.Url(code.PairKey),
            ["text"] = code.Format()
        };
    }

    private static JsonObject ComputeInviteLink(JsonNode input)
    {
        var invite = new InviteLink(new Uri(Text(input, "gateway")), Text(input, "inviteId"), Binary(input, "secret"));
        return new JsonObject
        {
            ["gateway"] = Text(input, "gateway"),
            ["inviteId"] = invite.InviteId,
            ["secret"] = Text(input, "secret"),
            ["pairKey"] = B64.Url(invite.PairKey),
            ["text"] = invite.Format()
        };
    }

    private static JsonObject ComputeAd(JsonNode item)
    {
        var args = item["args"]!;
        var builder = Text(item, "builder");
        var bytes = builder switch
        {
            "task" => Ad.Task(Text(args, "hostId"), Text(args, "taskId"), Text(args, "workspaceId")),
            "command" => Ad.Command(Text(args, "hostId"), Text(args, "commandId"), Enum.Parse<CommandKind>(Text(args, "kind"))),
            "event" => Ad.Event(Text(args, "hostId"), Text(args, "runId"), args["sequence"]!.GetValue<long>(),
                Enum.Parse<RemoteEventKind>(Text(args, "kind"))),
            "approval" => Ad.Approval(Text(args, "hostId"), Text(args, "runId"), Text(args, "approvalId"), Text(args, "toolCallId"),
                Text(args, "actionHash"), args["remoteDecidable"]!.GetValue<bool>()),
            "workspace" => Ad.Workspace(Text(args, "hostId"), Text(args, "workspaceId")),
            _ => throw new InvalidOperationException($"The vectors name an associated-data builder that does not exist: {builder}")
        };
        return new JsonObject { ["builder"] = builder, ["args"] = args.DeepClone(), ["bytes"] = B64.Url(bytes) };
    }

    // ---- small helpers ------------------------------------------------------------------------------------

    private static JsonObject CanonicalCase(string version, params string[] fields)
        => new() { ["version"] = version, ["fields"] = new JsonArray(fields.Select(f => (JsonNode)f).ToArray()) };

    private static JsonObject KdfCase(string info) => KdfCase(Encoding.UTF8.GetBytes(info));

    private static JsonObject KdfCase(byte[] info)
        => new() { ["ikm"] = B64.Url(RandomNumberGenerator.GetBytes(32)), ["info"] = B64.Url(info) };

    private static JsonObject EnvelopeCase(byte[] key, uint epoch, byte[] ad, string plaintext) => new()
    {
        ["key"] = B64.Url(key),
        ["epoch"] = epoch,
        ["nonce"] = B64.Url(RandomNumberGenerator.GetBytes(12)),
        ["ad"] = B64.Url(ad),
        ["plaintext"] = plaintext
    };

    private static JsonObject ActionCase(string runId, string toolCallId, string tool, string workingDirectory, string argumentsJson) => new()
    {
        ["runId"] = runId,
        ["toolCallId"] = toolCallId,
        ["tool"] = tool,
        ["workingDirectory"] = workingDirectory,
        ["argumentsJson"] = argumentsJson
    };

    private static JsonObject ApprovalCase(string hostId, string runId, string approvalId, string toolCallId, string actionHash, bool remoteDecidable) => new()
    {
        ["builder"] = "approval",
        ["args"] = new JsonObject
        {
            ["hostId"] = hostId,
            ["runId"] = runId,
            ["approvalId"] = approvalId,
            ["toolCallId"] = toolCallId,
            ["actionHash"] = actionHash,
            ["remoteDecidable"] = remoteDecidable
        }
    };

    private static JsonArray Each(JsonNode? items, Func<JsonNode, JsonObject> compute)
        => new(items!.AsArray().Select(item => (JsonNode)compute(item!)).ToArray());

    private static string Text(JsonNode node, string member) => node[member]!.GetValue<string>();

    private static byte[] Binary(JsonNode node, string member) => B64.FromUrl(Text(node, member));

    /// <summary>A private key as WebCrypto's JWK carries it, so the browser imports the stored values without conversion.</summary>
    private static JsonObject Export(ECDiffieHellman key)
    {
        var parameters = key.ExportParameters(includePrivateParameters: true);
        return new JsonObject
        {
            ["d"] = B64.Url(parameters.D!),
            ["x"] = B64.Url(parameters.Q.X!),
            ["y"] = B64.Url(parameters.Q.Y!)
        };
    }

    private static ECDiffieHellman Import(JsonNode jwk) => ECDiffieHellman.Create(new ECParameters
    {
        Curve = ECCurve.NamedCurves.nistP256,
        D = Binary(jwk, "d"),
        Q = new ECPoint { X = Binary(jwk, "x"), Y = Binary(jwk, "y") }
    });
}
